[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "task-manager"
version = "0.1.0"
description = "Task Manager Application"

[tool.setuptools]
packages = ["src"]
package-dir = {"" = "."} 